### PR TITLE
Add Asyncio Support

### PR DESCRIPTION
**Pull request by acspike**
Changes as discussed in Issue #47. 

I'm currently researching how to write and run tests for this new functionality. Pointer welcome.

### CODE REVIEW

**Comment by exhuma** [comment]
If it's OK for you I will leave it open until you have found a way to add tests? If I get around to do it, I will have a look myself. But I'm not sure I will get around to it in the coming week or so.

Additionally I just realised that the module names contain underscores. I'm not strongly against it, but it is [not recommended by PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)

I think there is still time to make `aio` a sub-package, and keep everything in that package. That it would become:

    from . import raw

instead of

    from . import aio_raw as raw

... it feels ... "nicer". I'm thinking of something like the following:

    puresnmp
    ├── aio
    │   ├── api
    │   │   ├── __init__.py
    │   │   ├── pythonic.py
    │   │   └── raw.py
    │   └── transport.py
    ├── api
    │   ├── __init__.py
    │   ├── pythonic.py
    │   └── raw.py
    ├── transport.py

What do you think?

It feels a bit weird to me to nest the parts you end up using that deep into the package, but on the one hand I don't want to refactor too much yet as I want to tackle a bigger refactoring operation anyway in the future (and in the process handle #3 as well).

**Comment by acspike** [comment]
Thanks, that's exactly the sort of input I was hoping for. I will make those changes. I'm not too concerned about the depth. I think the alternative is really to implement asyncio support in a separate project and I'd rather keep it together.

Is there documentation about running the tests?

**Comment by exhuma** [comment]
I'm hijacking this thread for a second to let you know that I am currently working on additional unit-tests which verify the return types of the currently published version of *puresnmp*. I have the gut feeling that I broke something when introducing the split with the "raw" and "pythonic" API. I want to avoid breaking existing code when publishing the new version.

I am fairly close to finishing these tests. I've begun merging into `develop` on my local box and have already identified some issues.

Given that you needed to copy most of the code of the existing files, you may also have duplicated the errors. Once I've identified those errors I will do my best to fix them in one single commit and tell you which commit it is in this thread. It shouldn't be a lot of changes.

**Comment by acspike** [comment]
I've had some success figuring out how to get travis to install the correct deps for tests and skip tests.

Since my intent is to use this code with python 3.6+ only and because python 3.5 does not support async generators, I am considering only writing the async code to support 3.6+. (The lowest I could go and continue to use the async/await syntax would be 3.5.) How do you feel going 3.6+ only?

**Comment by exhuma** [comment]
> How do you feel going 3.6+ only?

I'm okay with it.

I'm using the package at work as well and our machines currently run at 3.5. Obviously I have not started with asyncio yet (but it's something I have on my radar for future releases of the application which uses `puresnmp`).

That being said: With the current work-load I don't imagine I will get around to implement asyncio any time soon and chances are that 3.6 will hit our servers before I do.

So I'm fine with it. If I have to wait on our machines to be upgraded in order to benefit from asyncio then so be it ;)

**Comment by acspike** [comment]
Awesome. I think I can rollback 5fbdc95 then. And I think everything, including test, is as ready as I can make it until you identify the breakage you mentioned. Thanks!

**Comment by exhuma** [comment]
Sounds good. As I haven't merged anything yet I'm also OK with using an interactive rebase to drop the commit you talk about instead of rolling it back. This would keep the history a bit cleaner. If you feel comfortable using it ;) If not, I'm also OK with a rollback/revert.

**Comment by exhuma** [comment]
Maybe you can add something like the following to `aio/__init__.py`:

    from sys import version_info
    if version_info < (3, 6):
        raise RuntimeError('asyncio support in puresnmp requires Python 3.6+')

`RuntimeError` seems to be the one that fits best, even though it's not really.... "runtime"? But none of the other builtin error match.

**Comment by exhuma** [comment]
.... I'm getting there. I unfortunately messed up a `git stash` operation which heavily messed up my workspace. I'm still cleaning up but I'm afraid my plan to get  the smallest possible diff possible is out the window. I'm now focusing on getting my code back working and will push as-is.

My plan was to get the backwards-compatible breakage fixed in a small diff so it might (with luck) cleanly apply to the aio parts.

If all this passes well, I think I'll pull in your changes manually into a local branch and try to fix my own mess :frowning_face: 

Unfortunately I only get 1-2 hours to work on this every other day.

**Comment by acspike** [comment]
I'm not sure how to accomplish the RuntimeError thing. (NotImplemented seems right to me.) But in either case importing the code is a SyntaxError in older versions of Python. I wouldn't be able to catch that unless I added a second layer of imports.

Feel free to push your changes when you get it working and let me merge them into the asyncio branch. I'll ask if I need help.

**Comment by acspike** [comment]
Which branch should I be merging in? develop or release 1.3.0?

**Comment by acspike** [comment]
Tests pass if I merge in develop. The important missing change seems to be 668252af56b0 which exists in develop but not in release/1.3.0

**Comment by exhuma** [comment]
Release 1.3 is finished. I just realise that I forgot to push the final version to pypi. So the best merge target would be `develop`.

I'm planning to go ahead with the next major release next. Trying to stay backwards compatible is currently blocking me too much.

**Comment by acspike** [comment]
Please check to see if there is anything else you would like me to do with this branch.

**Comment by exhuma** [comment]
Sorry for the delay. I'm flip-flopping between several projects at the moment which makes everything go relatively slow...

Merged into current development branch.

I'm still receiving quite a lot of warnings about non-awaited coroutines when running the tests locally. Example:

```
puresnmp/test/test_aio_raw.py::TestGetNext::()::test_getnext
  /home/exhuma/work/puresnmp/env/lib/python3.6/site-packages/_pytest/python.py:143: RuntimeWarning: coroutine 'TestGetNext.test_getnext' was never awaited
    testfunction(**testargs)
```

As they are only warnings, I'm okay with merging this, but if you have some time I would appreciate it to address this. It makes console output of the unit-tests quite long.

I'm still working on a small bugfix caused by non-determinism of dictionaries. Once that hits `master`, I will work on a `1.4.` feature release for the asyncio support.

**Comment by acspike** [comment]
Could you check the output of `pip freeze`. I had to add a few packages to test the async parts. What you are describing sounds a little like you don't have `pytest-asyncio` installed.

**Comment by exhuma** [comment]
Ah indeed. I see it is already in the test-requirements in `setup.py`. So all is good.

My bad for not re-executing the setup step during my tests.

nb: I am currently investigating a potential problem: I noticed that [one test fails on Python2](https://github.com/exhuma/puresnmp/blob/develop/puresnmp/test/test_raw.py#L186) and did not give it much thought until recently. I noticed that travis fails on the same test in Python 3.5 as well. On my machine I have Python 3.6 and have a very strong suspicion that it is due to the fact that dictionaries keep their ordering starting with 3.6, but not before. In the worst case, depending on where it originates from, this issue might also have an impact on the asyncio API.

I am looking through it as I write this and have a suspicion that it may be in `util.group_varbinds` or `util.get_unfinished_oids` in which case it would be shared code between the asyncio and non-asyncio parts.

I will see how far I get today looking this through, because this would be a fairly serious issue...

**Comment by exhuma** [comment]
I've identified the culprit, and it was unfortunately in the part of the code which had to be duplicated for asycio support (inside `raw.py`). I have published the hotfix branch (based off `master`) so you can have a look at it: https://github.com/exhuma/puresnmp/commits/hotfix/1.3.2-python35

I also created a branch based off your `asyncio` branch and integrated the changes. I also took the opportunity to sync it up with the latest changes made in `raw.py` (the final commit in that branch). Unfortunately, the `aio` unit-tests fail now with a `StopIteration` error. Unfortunately I have to run off again for today. Can you have a look at it?

https://github.com/exhuma/puresnmp/commits/fix-nondeterminism-asyncio

**Comment by acspike** [comment]
It looks like something is causing the mock to be called past three supplied side_effect values. Not sure why this would only be triggered in the aio version. The code is almost identical.

**Pull request merged**
