### PR TITLE
Update types.py

### PR DESCRIPTION
**Pull request by alexxxe**
It have been seen that under specific vendor response  with bad corrupted data the received value can be significantly larger than integer and current code will take it for a long processing time by blocking other code being running. The suggested code will improve the processing time in this case.

### CODE REVIEW

**Comment by exhuma** [comment]
Thanks for the PR. I will merge and release this in a moment.

**Comment by exhuma** [comment]
Upon review, I see that this fails unit-tests. I need to check why the CI pipeline did not detect this.

Can you review the unit-tests please?

**Comment by alexxxe** [comment]
> Upon review, I see that this fails unit-tests. I need to check why the CI pipeline did not detect this.
> 
> Can you review the unit-tests please?

Done. Fixed boundaries & formatting

**Comment by exhuma** [comment]
Thanks. Has been released as [v1.10.2](https://pypi.org/project/puresnmp/#history)

**Pull request merged**
