### PR TITLE
Allow using of SNMPv1 for some get requests

### PR DESCRIPTION
**Pull request by revmischa**

### CODE REVIEW

**Comment by exhuma** [comment]
This is awesome. Thanks for this. Simple changes with big impact 😉  I like it!

Would you mind adding a few unit-tests for these as well? Have a look at the existing tests for [get](https://github.com/exhuma/puresnmp/blob/85af0550a52053d4b44a2b905ce5cdd6af2f677e/puresnmp/test/external_api/test_v1.py#L64) to get you started. It should not be too difficult. If you want to add new hex-dumps for mocked responses, they can go into [puresnmp/test/data](https://github.com/exhuma/puresnmp/tree/develop/puresnmp/test/data).

Finally, could you tell me which SNMPv1 calls you tested? So I can update the docs accordingly.

**Comment by revmischa** [comment]
multiget, multigetnext, bulkget, multiwalk

**Comment by adamszeptycki** [comment]
Any updates on this one? Would love to use it in my project

**Comment by revmischa** [comment]
@exhuma need anything else here?

**Comment by revmischa** [comment]
Any chance this could be released sometime soon?

**Comment by exhuma** [comment]
Sorry for the silence. I'll merge it and add it to the next release.

**Comment by revmischa** [comment]
Thank you, any chance you could do a release of this please? Would appreciate it

**Comment by exhuma** [comment]
Sorry for the delay/silence, I was busy with other projects. I'll have a look about  the release. I actually thought I already did, so thanks for bumping me on this.

I'm currently investigating [rfc-3411](https://tools.ietf.org/html/rfc3411) in order to prepare for SNMPv3 (but I'm still a bit lost in the jungle 😉 ) so I got side-tracked a bit.

**Comment by exhuma** [comment]
Has been released as 1.9.0

**Comment by revmischa** [comment]
Thanks! 💯

**Pull request merged**
